### ISSUE TITLE
Add "Must bump version" check

### ISSUE THREAD

**Issue by dreispt** [OCA/pylint-odoo#59] opened 2016-08-02 11:19 UTC
This is a suggestion for a new check:

When doing a PR, it should bump the module's version should be bumped, either if we are porting, adding feature, or fixing code.
The check should run only for PRs.

Special case: some PR might not involve modules (e.g: changir .travis.yml) - in these case the check should not fail.

**Comment by max3903** [comment] 2016-08-02 14:25
:+1:

**Comment by moylop260** [comment] 2016-08-02 15:13
Its is posible if you add `version` in required keys from configuration file of PR from mqt

https://github.com/OCA/maintainer-quality-tools/blob/master/travis/cfg/travis_run_pylint_pr.cfg#L14

**Comment by moylop260** [comment] 2016-08-02 15:16
Or are you talking about auto increase the version number to manifest file?

Like as a plugin to odoo modules of https://pypi.python.org/pypi/bumpversion/0.5.3?

**Comment by sebastienbeau** [comment] 2016-08-02 15:27
:+1: for adding the check.
bumpversion can be a good tool for incrementing the version

**Comment by dreispt** [comment] 2016-08-02 16:01
The point is not to autoincrement (that depends on the type of change made).
The point is to check that we don't forget to change the version number when doing a PR.
You don't even have to check if it increases, it's enough to check if it changed.

**Comment by moylop260** [comment] 2016-08-02 16:18
@dreispt 
Thanks for clarify
I got it

I'm agree with you

What about if 2 people are working in 2 different changes?
The PRs will tend to diverge with conflicts because change the same line.
If PR1 is merged the PR2 will show conflicts or viceversa.
And the reviewers will request to contributors that fix the conflict but this could be requested many times by each PR merged of the same module.

Generally in many projects the change of versions are controlled from stable branch to avoid this issues.

IMHO we should think use a workflow (auto or manual) to change it from stable branch.

**Comment by elicoidal** [comment] 2016-08-02 23:07
:+1: with the check
:-1: for auto-increment

**Comment by dreispt** [comment] 2016-08-03 14:15
@moylop260 I think that's a corner case we can live with. And if two people are changing the same module, odds are that you will have conflicts and need a rebase.

**Comment by moylop260** [comment] 2016-10-18 12:43
Could somebody help me to create this check?

If you want help use the following videos to learn
https://asciinema.org/a/26890
https://asciinema.org/a/26889

**Comment by moylop260** [comment] 2016-10-18 12:56
Maybe this check is not a `pylint-odoo` one.
Because we need extract a `git diff` and verify if there is a `manifest version` change and pylint-odoo is not using a `git diff`

IMHO It's a new script from MQT, since we have [git_run](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/git_run.py) script to know a `git diff` of items changed.

**Comment by sbidoul** [comment] 2016-10-19 17:01
Actually I'm not sure bumping version at each PR is the right thing to do.

In "normal" projects the maintainer bumps the version when he does a release. Between releases there is dev, alpha and beta versions.

If we want to encourage faster merges (aka optimistic merges) we need a mechanism to mark releases that the maintainer deems stable.

So in the current state of affairs, I believe it's better to *not* force bumping versions in each PR and let the maintainer do it manually when he thinks the module is stable enough.

**Comment by moylop260** [comment] 2016-10-19 17:07
+1 with @sbidoul

**Comment by dreispt** [comment] 2016-10-19 20:44
@sbidoul AFAICT in OCA world every PR merge is a stable release.

**Comment by dreispt** [comment] 2016-10-19 20:46
To make it clear: my suggestion is not for automatic version bumping - that should be a human action, since we must decide what digit to bump.
I'm suggesting to check that a PR always bumps (or at least changes) the module version number.

**Comment by sbidoul** [comment] 2016-10-19 20:51
> in OCA world every PR merge is a stable release.

Yes, and I think we must strive to change that. 

That's why I'm :-1: on this check: encouraging people to bump version at each merge would make it harder to transition to optimistic merge + manual release.

**Comment by lasley** [comment] 2016-10-19 20:55
I think that we will need a better tagging mechanism if we start releasing non-stable versions, with beta/alpha tags excluded from the Odoo Apps store & everyone's automatic upgrade systems. Stable module one day, broken the next - not really the way to go IMO.

**Comment by moylop260** [comment] 2016-10-19 21:52
Maybe we are seeing the modules like as a python package.
I showed in OCA sprint to @sbidoul How to auto bump version in python package with a release/tag after merge.
(I know here the matter is not auto-bump version)

The point is that working with python package you don't change the version in each PR.

Imagine 3 developers working in a PR in the same module.

| Module           | Developer      | Stable version     | Bumped version |  Status of PR |
|-----------------|---------------|--------------|--------------|--------------|
| Module A | Tom  | 8.0.1.0.0 | 8.0.1.0.1 | Open |
| Module A |        Jhon       |    8.0.1.0.0          | 8.0.1.0.1 | Open |
| Module A |        Jarry       |         8.0.1.0.0     | 8.0.1.0.1 | Open | 

After days of feedback and more commits a PR is merged.

| Module           | Developer      | Stable version     | Bumped version |  Status of PR |
|-----------------|---------------|--------------|--------------|--------------|
| Module A | Tom  | 8.0.1.0.0 | 8.0.1.0.1 | Merged |
| Module A |        Jhon       |    8.0.1.0.0          | 8.0.1.0.1 | Conflicts manifest file |
| Module A |        Jarry       |         8.0.1.0.0     | 8.0.1.0.1 | Conflicts manifest file |

After fix conflicts

| Module           | Developer      | Stable version     | Bumped version |  Status of PR |
|-----------------|---------------|--------------|--------------|--------------|
| Module A |        Jhon       |    8.0.1.0.1          | 8.0.1.0.2 | Open (Rebased) |
| Module A |        Jarry       |         8.0.1.0.1     | 8.0.1.0.2 | Open (Rebased) |

After days of feedback and more commits a PR is merged.

| Module           | Developer      | Stable version     | Bumped version |  Status of PR |
|-----------------|---------------|--------------|--------------|--------------|
| Module A |        Jhon       |    8.0.1.0.1          | 8.0.1.0.2 | Conflicts manifest file |
| Module A |        Jarry       |         8.0.1.0.1     | 8.0.1.0.2 | Merged |

After fix conflicts (Again)

| Module           | Developer      | Stable version     | Bumped version |  Status of PR |
|-----------------|---------------|--------------|--------------|--------------|
| Module A |        Jhon       |    8.0.1.0.2         | 8.0.1.0.3 | Open (Rebased*2) |

IMHO a bump version is not work of a pull request.
If a process increase the conflicts of a PR create a game that discourage new contributions.

I my case if I see a opened PR of the same module... better I will wait a merge before of create my PR today  in order to avoid the game of conflicts, fix, rebase, conflicts, fix, rebase...

IMHO It should be work of the maintainer who decide what PR merge first.
But this is a work that the maintainer don't want to do.

For pylint-odoo we are using [pbr](https://pypi.python.org/pypi/pbr/) and if we create a new `git tag -s v8.0.1.0.2 {SHA}` then a [release](https://github.com/OCA/pylint-odoo/releases) is auto-created and a new version is auto-deployed in pypi.

We decide the version with the tag.

Other tools to bumpversion is [bumpversion](https://pypi.python.org/pypi/bumpversion) to auto increase the version `{major.minor.patch}` use the following commands:
  - For increase .patch section
     -  `bumpversion patch --tag`
  - For increase .minor section
     -  `bumpversion minor --tag`
  - For increase .major section
     - `bumpversion major --tag`

This auto-create a commit, a tag and change the manifest.

We decide the version with the patch|minor|major command.

Maybe, we can use a mix of pbr and bumpversion to change the manifest version based in (something):
 - Maybe a standard of commit message
 - Maybe a tag for each module
 - Maybe a mix of: auto-increase just patch sections but for minor and major use manually.

I don't know what is the better solution for 2 worlds.

**Comment by moylop260** [comment] 2016-10-19 21:59
@lmignon What is you opinion for this?

**Comment by max3903** [comment] 2016-10-19 22:08
If there is many PR on the same module, the second PR should be made
against the first one, not the OCA branch.

[image: Ursa Information Systems]
*Maxime Chambreuil**Project Manager / Consultant*

Ursa Information Systems
1450 W Guadalupe Road, Suite 132
Gilbert, Arizona, 85233



* Office:     1-855-URSA ERP x 710                 1-855-877 2377 x 710
Mobile:   1-602-427-5632*

**Comment by moylop260** [comment] 2016-10-19 22:11
@max3903 I dont understood sorry
Could you help me to clear it?

**Comment by max3903** [comment] 2016-10-19 22:16
Instead of having 3 PR opened against the OCA branch. The second and third
PR should be made against the branch of the first PR.

One example:
1st PR: https://github.com/OCA/server-tools/pull/543
2nd PR: https://github.com/naousse/server-tools/pull/1

[image: Ursa Information Systems]
*Maxime Chambreuil**Project Manager / Consultant*

Ursa Information Systems
1450 W Guadalupe Road, Suite 132
Gilbert, Arizona, 85233



* Office:     1-855-URSA ERP x 710                 1-855-877 2377 x 710
Mobile:   1-602-427-5632*

**Comment by sbidoul** [comment] 2016-10-19 22:18
> If there is many PR on the same module, the second PR should be made against the first one, not the OCA branch.

This is most unusual.

**Comment by max3903** [comment] 2016-10-19 22:21
Also, if there is 3 PR on the same module, maybe an issue should have been
created in the first place... but this is another topic and I agree
unusual, but we can improve and encourage good behavior, right?

[image: Ursa Information Systems]
*Maxime Chambreuil**Project Manager / Consultant*

Ursa Information Systems
1450 W Guadalupe Road, Suite 132
Gilbert, Arizona, 85233



* Office:     1-855-URSA ERP x 710                 1-855-877 2377 x 710
Mobile:   1-602-427-5632*

**Comment by sbidoul** [comment] 2016-10-19 22:24
FWIW `setuptools-odoo` already auto-bumps dev versions in packaged addons distributions, based on the number of commits since last version change (similar to what pbr does). Have a look at https://wheelhouse.odoo-community.org/oca

**Comment by lasley** [comment] 2016-10-19 22:39
> Imagine 3 developers working in a PR in the same module.

You raise a good point. I am coming around to see the need for the version bump being outside of the PR. Here's an example of PRs submitted to the same module, all with independent purposes and no conflicts between them (from what I remember):

* https://github.com/OCA/connector/pull/216
* https://github.com/OCA/connector/pull/215
* https://github.com/OCA/connector/pull/213

None of these PRs raised the patch version in the manifest. Had we tried to do so, the respective authors would have had to watch for other authors' PRs to possibly get merged in front of their's.

While our amazing concept of modularity does keep us from this in most cases, it does happen.

> Instead of having 3 PR opened against the OCA branch. The second and third PR should be made against the branch of the first PR.

IMO this only holds true if the PRs are linked to each other in some way. If I author a bug fix, I don't expect to become responsible for a feature addition due to a PR being submitted to my branch. This could also cause lost PRs if they are being submitted to not-so-responsive repos.

**Comment by moylop260** [comment] 2016-10-19 23:47
Using `odoo.version.breaking.feature.fix` version standard most of the time we are creating many changes of last digit:
 - 5% odoo.version
  - Increment it manually
 - 10% .breaking
  - Increment it manually
 - 15% .feature
  - Increment it manually
 - 70% .fix
  - Increment it automatically (If the version is not changed)
    - We can use the transifex travis build to add a extra commit with the bump version similar to @sbidoul script.

**Comment by lmignon** [comment] 2016-10-20 07:41
@moylop260 I like the idea to auto increment the .fix number (if .breaking or .feature or .fix are not already incremented) on merge. IMO that should be done in a dedicated script (no transifex) and use the @sbidoul script.

**Comment by Yajo** [comment] 2016-10-20 07:51
Well, for those who don't like this requirement, let me quote myself from https://github.com/OCA/maintainer-quality-tools/issues/376#issue-183622844:

> The rationale behind this is that I'm thinking of some sort of autoupdate addon that updates all addons whose current version does not match the currently installed one. Kinda "update all", but only what is needed and automatically, to get less failures in case an addon gets updated.

As some may have noticed, OCA grows usually more than what most of us can control. And having updatealls all the time is not fun because it is more downtime for no benefit. So the only way to create an addon with a cron that automates updates is to check installed version vs. available version. Well, option B would be to analyze git diffs, but git is not something we actually need in production in these Docker and pip days.

If we want to have such automation, but avoid https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254951868, then I also vote for the proposal of @moylop260 in https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254972623, with an additional benefit of Transifex updates raising versions :tada:. 
In fact, a real nice check would be one that installs old addon, then runs tests, then updates to new, then runs tests, but that's another issue.

OTOH, I have absolutely no idea on how to do that, I hope someone does...

**Comment by sbidoul** [comment] 2016-10-20 08:02
If people want the automation, I suggest a variant with 6 positions: `odoo.version.breaking.feature.fix.dev` where `dev` is the number of commits since the last commit changing the version in the manifest.

So we leave `breaking.feature.fix` as a manual indicator of stable releases (as usual in normal projects), and `dev` being the automatic increment.

An algorithm to compute `dev` is here: https://github.com/acsone/setuptools-odoo/blob/master/setuptools_odoo/git_postversion.py

**Comment by Yajo** [comment] 2016-10-20 08:24
I think [that should be `odoo.version.breaking.feature.fix-dev` then](https://github.com/odoo/odoo/blob/9.0/openerp/tools/parse_version.py#L82), but in any case I still prefer https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254972623. After all, if a patch landed and no breaking nor feature is incremented, then that means it is a fix (or translation, which can be considered a fix too for people that talk that language).

Besides, adding a commit that tells you how many commits since the last commit is recursive...

**Comment by dreispt** [comment] 2016-10-20 08:44
I tend to dislike automatic changes to modules, since it adds more magic and machinery, and that kind of stuff tends to bite us back sooner or later.
But I won't oppose.

@sbidoul Nice suggestion. How about the 5 position `odoo.version.breaking.feature.dev`?

**Comment by Yajo** [comment] 2016-10-20 08:45
Actually manual things are the ones that break things :stuck_out_tongue_winking_eye:

**Comment by sbidoul** [comment] 2016-10-20 09:47
I like to have the `breaking.feature.fix` part updated manually by the maintainer, to declare stable releases of any type (including bugfix releases). 

It's quite common to have an additional position (different from the bug fix position) to mark developmental unreleased versions.

I personally don't need the 6th position to be updated automatically (as setuptools-odoo does it when packaging) but if some people like to have it, I'm perfectly fine with that and I believe the algorithm in https://github.com/acsone/setuptools-odoo/blob/master/setuptools_odoo/git_postversion.py is applicable to do that.

**Comment by Yajo** [comment] 2016-10-20 11:05
> I like to have the breaking.feature.fix part updated manually by the maintainer, to declare stable releases of any type (including bugfix releases). 

The problem with that is that we would still hit https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254951868.

@moylop260's solution implies that developers _should **not**_ manually increase `fix`, but rely in the automatic trigger instead.

But if the developer never increases `fix` and the trigger only increases `dev`, then `fix` would always be zero, and then `fix` would become useless, so we could simply remove `fix`... but then `dev` becomes `fix`, so it's the same as removing `dev` and leaving versioning schema exactly as it is right now.

--
as a side note: setuptools-odoo updates the pip version, not the version Odoo sees. That must be updated in the `__openerp__.py` file (`__manifest__.py` for > 10) for him to see it AFAIK.

**Comment by sbidoul** [comment] 2016-10-20 11:16
> But if the developer never increases fix and the trigger only increases dev

@Yajo we could extend your reasoning to the other components (breaking, feature). In the end if the maintainer does not do his release management/versioning job, then there is a problem.

My point is that we should not try to reinvent processes in OCA. In the vast majority of projects the 3 main components of the version (major.minor.fix) are bumped manually when a version is stable/released. I see no good reason to do differently in OCA.

**Comment by Yajo** [comment] 2016-10-20 12:14
Yes, I get your point, but how would you avoid https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254951868 then?

**Comment by sbidoul** [comment] 2016-10-20 12:21
@Yajo avoid what exactly? (that comment si very long)

**Comment by Yajo** [comment] 2016-10-20 12:29
Avoid having several PR open at the same time, all of them bumping the `fix` number, forcing each of them do a rebase each time another one is merged. After all, no PR has sense without a version increase.

**Comment by sbidoul** [comment] 2016-10-20 12:35
Creating PR is the role of *contributors*. Contributors don't change the `breaking.feature.fix`.

Updating `breaking.feature.fix` is the responsibility of *maintainers*. That must be done after merging if the maintainer deems the PR safe enough to be stable, or later, possibly after merging several PR's.

So IMO, PR's must *not* change the version.

**Comment by lmignon** [comment] 2016-10-20 12:55
Am I wrong by saying that what we need is a proper release policy where the PSC/maintainers are in charge to increase the version number, create a new tag, .... .

**Comment by Yajo** [comment] 2016-10-20 13:06
I think that is definitely wrong, friends. This thread is about _automating_ the version number bump, either by adding a check or adding an automated action. You are trying instead to move it to a policy change where maintainers have _an additional manual burden_. Sorry but not, that makes no sense.

Why would a PR get merged if it is not stable enough? Stability must be reached in the PR stage, where the review process takes place, not after merging.

The PR issuer is the one who must comply with all Travis checks, and that's why we were asking for this check in the first place. He is also the one that knows if the change is a breaking, feature or fix. Yes, maintainers can help now that there is the GH tool of allow changes from maintainers, but PR should get cleaned before merging, not after.

And I think you are missing https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254935238.

> So IMO, PR's must not change the version.

[Guidelines are clear](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers). If you don't increase the version number, is because your patch does not fit into any of those categories. Could you provide an example for that? Personally, I can't imagine any.

**Comment by lmignon** [comment] 2016-10-20 13:30
@Yajo IMO OCA lacks of a proper release process. In other communities it's easy to known the list of changes between 2 releases, you are able to see the changes into the code between 2 releases just by comparing 2 tags, .... I don't want to add an additional manual burden on the maintainers. As you can see in one of my previous comments I also supported the idea of an automatic bump of version number. But the comments from others allow me to see the problem from another point of view and finally I wonder if this auto bump is not such a good idea.

**Comment by sbidoul** [comment] 2016-10-20 14:48
@Yajo guidelines wrt versioning are clear and correct indeed. I don't question that. Note it's not written in the guidelines that each PR must bump `breaking.feature.fix`.

What I say is that the current OCA approach where merge = release is considered harmful. This slows down merges and creates stress and risk. Therefore I advocate progressively evolving towards a process that is more standard in open source projects:

- contributors make PR
- maintainers review and merge them rapidly even if they are not 100% perfect, provided they pass automated quality tests
- maintainers do releases when they deem the code stable

Note it is only a small variation on the existing OCA process.

The best/easiest way we have to signal a release is to bump `breaking.feature.fix`. All I say is that this must be a human decision. If an automated bump is needed it can be done after merge and on a 4th position `breaking.feature.fix.dev`.

**Comment by pedrobaeza** [comment] 2016-10-20 15:03
@sbidoul, I don't agree with that change in the process, because at the end, who will test that "beta" merge to bump the version? I don't see any advantage in that change, and more disadvantages and work that is not tracked the same as is done in the PRs.

**Comment by lasley** [comment] 2016-10-21 02:05
IMO the main thing holding us back from a proper release process is having multiple modules in a repo. I don't see a way to perform the tags necessary in any meaningful way, so we seem to need another option.

Sorry if this is a newb question, but how would migrations be affected (assuming we did go with the auto-bump)? Let's say for example:

* Breaking (9.0.2.0.0) is added & a col type is changed from int to float
* Migration is created for 9.0.2.0.0 version
* Fix is merged a few days later, auto-bump to 9.0.2.0.1

If the user upgrades from 9.0.1.0.0 to 9.0.2.0.1, is the 9.0.2.0.0 migration still run?

**Comment by lmignon** [comment] 2016-10-21 05:27
@lasley 
> If the user upgrades from 9.0.1.0.0 to 9.0.2.0.1, is the 9.0.2.0.0 migration still run?
Yes it is.

**Comment by Yajo** [comment] 2016-10-24 08:09
> the current OCA approach where merge = release is considered harmful

What you consider harmful I consider one of the best strengths of OCA.

Besides, OCA has stable branches: those with names like `8.0`, `9.0`, `10.0`, etc.; and it has development branches: [those with names like `pull/###/head`](https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally), I see no need for change there. You can checkout/merge/open PR to the one you want.

The **problem** here is that we have some guidelines on versioning, but they are not actually being followed because either devs are not forced to do so or they are not automated, thus there is no _reliable_ way for Odoo to know if an addon had an update.

The **solutions** AFAICS are:

1. Add a check in travis.
   - + Devs must go :white_check_mark: with bots, it's 1 LOC change, so not much harm.
   - - [Several PR for same addon at the same time would conflict](https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254951868).
2. [Autobump last number (5th position, `fix`). Manual bump on others.
](https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254972623)
   - + Most fixes will raise version automatically.
   - + Devs must still do manual update when a breaking change is included.
   - + Can be automated for Transifex commits too.
   - + No changes on guidelines.
3. [Autobump last number (6th position, `dev`). Manual bump on others.
](https://github.com/OCA/pylint-odoo/issues/59#issuecomment-254972623)
   - - Changes guidelines.
   - - Aims to change current workflow.
   - - Aims to merge unstable & stable code in the same branch.
   - + Most fixes will raise version automatically.
   - - Although that would have no benefit because additional manual work should be done by maintainers.
   - + Faster merges (although that's not a + for me...)
   - - Blurs the distinction between a `fix` and a `dev`. Seriously, what PR that is not a `breaking`, `improvement` nor `fix` could ever exist anywhere?
4. Forget this. `--update all` always.
   - + It works out of the box and right now.
   - - Quite a few downtime in big installations.
   - - Most downtime is spent updating things that are updated already.

My vote goes for option 2. Cast your votes please.

Please correct me if I forgot some option/pro/con.

--
As a side note, I'm thinking also on another approach for option 4, that could be also applied for option 2 if ever implemented:

0. Add a flag to warn your users about maintenance status.
0. Forbid updates for the currently connected Postgres user, restricting its permissions.
0. Duplicate the database.
0. Connect the outdated Odoo to the duplicate.
0. Restore write permissions in original DB.
0. Wake up an updated Odoo instance with `--update all` on the original database.
0. Shut down the outdated Odoo when the updated one finishes the update.
0. Wake up the updated one.
0. Destroy containers for old DB duplicate and old Odoo instance.

Yes, that would take a bigger amount of time, but it would be automatic and would mean close to zero downtime in the user's face. Well, they'd have some read-only time, but that's better than downtime.

Just thinking out loud.

**Comment by dreispt** [comment] 2016-10-24 08:48
IMO two PRs targetting the same module is not such a frequent event, so keeping the process manual is an option. If you make a PR, you are expected to bump the version, so my proposal here is for MQT Lint to check that the version was changed.

If someone wants to implement automatic version bumping, that's a nice to have, and I would go for option 2, keeping the already long 5 digit version numbers, and avoiding an even longer 6 digits versions.

**Comment by moylop260** [comment] 2016-10-24 13:50
My vote is for option 2

**Comment by lmignon** [comment] 2016-10-24 14:06
My vote is for keeping the process manual. If the automatic version bumping is put in place we must provide a way to disable this automatic process.

**Comment by lasley** [comment] 2016-10-24 15:24
My vote is option 2- auto-bump on 5th position

**Comment by sbidoul** [comment] 2016-10-25 06:41
My vote is for bumping the version manually after merge. I exposed my arguments above. The main reason is that in open source processes, managing version number is the responsibility of the maintainer, not the contributor.

**Comment by Yajo** [comment] 2016-10-25 07:45
Thanks, I'm updating https://github.com/OCA/pylint-odoo/issues/59#issuecomment-255674953 with votes to have all clear.

I added 5th option from https://github.com/OCA/pylint-odoo/issues/59#issuecomment-255950243.

@lmignon By manual do you mean option 1, 4 or 5?

**Comment by sbidoul** [comment] 2016-10-25 07:56
@Yajo if you consolidate votes in the same comment, please make sure to include all +/- arguments too.

**Comment by Yajo** [comment] 2016-10-25 07:57
I'm trying to, please tell me the +/- points you miss for any of them :wink:

**Comment by sbidoul** [comment] 2016-10-25 08:09
@Yajo for instance you do not reflect my argument about staying close to usual open source processes. Also when you say "aims to change current workflow" this is not accurate. I do not want to change the current workflow now, I want to keep the door open to evolving the current workflow. This is quite different.

**Comment by Yajo** [comment] 2016-10-25 08:15
Thanks, I changed both. If you miss any other points, please tell.

**Comment by NL66278** [comment] 2016-10-25 08:17
My vote is for option 2: autobump last position (fix), manually change others.

**Comment by lmignon** [comment] 2016-10-25 08:54
@Yajo 
> @lmignon By manual do you mean option 1, 4 or 5?

option 5 must stay the default and the auto bumping version must be a decision by project/PSC. Therefore the autobump can't be put by default on each project.

**Comment by simahawk** [comment] 2016-10-25 10:02
I vote for opt 2 too

**Comment by pedrobaeza** [comment] 2016-10-25 10:06
My vote diverges a bit, but it's something that has already be said: we must check in MQT that the version is changed on each PR (that is to force user to change it), but leave the user to decide which part he/she changes according the PR. Conflicts because of this won't be the usual day to day.

**Comment by simahawk** [comment] 2016-10-25 10:16
What if opt 2 could be tied to a keyword in PR name? Like: `[FIX] bla bla` -> change "fix" part.

**Comment by Yajo** [comment] 2016-10-25 10:18
If possible, it would be cool. You mean trigger the linter (opt.1) if `[FIX]` is not in the title, trigger the autoupdate (opt.2) otherwise, right?

**Comment by simahawk** [comment] 2016-10-25 10:22
yep, would be nice and make everybody happy... I guess :)

**Comment by Yajo** [comment] 2016-10-25 10:27
Nice, option 7 added, I switch our votes for that. :wink:

**Comment by yvaucher** [comment] 2016-10-25 11:59
For me the bump for fix and improvement is something that must be done the merging process.
While for port and big refactoring I think this could be done by the author of the PR.

However, if we can simply automate it, it would be great.

We have 4 cases to take care of:

automated (to do while merging, responsibility of the merger):
[FIX] for x.x.y.y.+1
[IMP] for x.x.y.+1.0

manually changed by commiter in the PR:
Big refactor or new major version
[REF] [other?] x.x.+1.0.0
Portage to Odoo version +1
[MIG] +1.0.1.0.0

Thus the check on title might not be necessary if version was manually changed.

Unless we want to force all PR title to a set of tags in which case we could extend the automated behavior to bigger changes like migration and major versions using tags in each PR title.

**Comment by Yajo** [comment] 2016-10-25 12:11
I think that could lead to problems. When we talk about a FIX, it always increases 5th number; but an IMP could increase the 4th number (if it is non-breaking) or the 3rd (if it is breaking). The responsibility to choose which one to increase in this case is for a human.

Also, the point for automatic bump is fix simultaneous PR conflicts. Yes, it could happen that 2 IMPs come at the same time for the same addon, but seems not so usual, and a rebase in that case could be required not just for the version but for the code too, so I would not lose too much time in making such a hard job that would just cover a random percent of contributions. Option 7 covers 100% of them.

BTW, having 2 MIG at the same time is out of scope; conflict is guaranteed, so nothing to do there.

In any case, I think that your suggestion could be applied in a later step (like v2.0 of the autobumper) if we go for option 7, so let me add it there with your vote.

**Comment by lasley** [comment] 2016-10-25 16:37
Option 7 seems like an ideal scenario, but IMO we will need to align our contribution docs for that. These prefixes aren't mentioned anywhere, so it will be unlikely for anyone other than veterans to get it right.

I like to hope for ideal scenario though, so my vote is changed to 7. With my vote on this side of the fence, I'll help out with the docs if it happens 😉

**Comment by pedrobaeza** [comment] 2016-10-25 16:45
You can take the section "Commit message" from Odoo guidelines as reference: https://www.odoo.com/documentation/8.0/reference/guidelines.html

**Comment by max3903** [comment] 2016-10-25 18:27
@sbidoul If we go with option 2, can we package the branches being reviewed
and use 'dev' and the PR #?

[image: Ursa Information Systems]
*Maxime Chambreuil**Project Manager / Consultant*

Ursa Information Systems
1450 W Guadalupe Road, Suite 132
Gilbert, Arizona, 85233



* Office:     1-855-URSA ERP x 710                 1-855-877 2377 x 710
Mobile:   1-602-427-5632*

**Comment by max3903** [comment] 2016-10-25 18:52
Can we coexist? Can we have PSC or repo where maintainers accepts PR easily
and do release management?

I would like to try to see if I get more contributions.

[image: Ursa Information Systems]
*Maxime Chambreuil**Project Manager / Consultant*

Ursa Information Systems
1450 W Guadalupe Road, Suite 132
Gilbert, Arizona, 85233



* Office:     1-855-URSA ERP x 710                 1-855-877 2377 x 710
Mobile:   1-602-427-5632*

**Comment by Yajo** [comment] 2016-10-26 08:00
> If we go with option 2, can we package the branches being reviewed and use 'dev' and the PR #? 

That effort goes well if you only need 1 PR to be merged in your deployment, but if that PR gets stalled or you need more than one, then you still need to do a git merge... And that happens a lot, from my experience.

> Can we coexist? Can we have PSC or repo where maintainers accepts PR easily and do release management? 

I wouldn't veto against that as long as stable branches are not affected. If you want to open a 8.0-unstable, 9.0-unstable, etc. branch and merge anything there, I have no problem; but the main reason we can officially support all the hundreds of OCA addons in many companies is the reliable stability filters that code passes before reaching stable.

Of course, I hope you agree that merges from i.e. 9.0-unstable to 9.0 should go through a PR.

But we are merging 2 issues here. One is the optimistic merge proposal, and other is the autobump one.

**Comment by sbidoul** [comment] 2016-10-26 08:04
> But we are merging 2 issues here. One is the optimistic merge proposal, and other is the autobump one.

@Yajo The problem is that autobump and optimistic merging are incompatible. That's why I advocate manual bump or as, @max3903 suggests, enabling autobump on a per project basis.

**Comment by sbidoul** [comment] 2016-10-26 08:07
> can we package the branches being reviewed and use 'dev' and the PR #?

@max3903 Packaging PR's is possible although not trivial. It's mostly unrelated to the option chosen here. Note it's very easy to pip install from a git branch directly (see my slides), so packaging of unmerged PR's is not necessary IMO.

**Comment by Yajo** [comment] 2016-10-26 08:50
Well... actually it's not autobump vs optimistic merging. Autobump automates the way OCA currently works, while optimistic merging changes it, so the incompatibility is only in the optimistic merging side of the battle.

That proposal should be discussed in a separate thread, please kindly open it somewhere, expose your arguments, and let's not block this one for that.

**Comment by dreispt** [comment] 2016-10-27 09:49
Solutions 1 and 5 are essentially the same thing - manual version bumping, basically as of today, and if possible a Lint check (warning or failing, to be decided).
I don't really understand what Solution 4 is.

**Comment by dreispt** [comment] 2016-10-27 09:55
@moylop260 Independently of the autobump discussion, is the "must bump version" check easy to add to pylint? 
IMO it is interesting to have it available, regardless of the discussion on how to enable it, or how to automate version numbers.

**Comment by Yajo** [comment] 2016-10-27 11:58
@dreispt Your questions are already answered; please read the thread :wink:

**Comment by mmalorni** [comment] 2016-10-28 12:11
Sorry for the long comment!
I vote for #1. I think all automated scripts will be error prone and maintenance heavy as we will not be able to foresee all issues and changes in policies. Since maintainers will do the merge, we can rely on their judgment to decide which digit to increase. This can even help with optimistic merge since in doubt only the last digit could be updated. We can use 6 digits at any point to identify unstable versions if the release process is fixed accordingly. That would help to move things along. Issues can stay open to note what still remains to be fixed and we can merge any PR that has been stalled for more than a week and allow other contributors to make another PR to finalize the work instead of being stuck in the waiting game. Of course, having a dev branch or dev repos would resolve this issue as well and allow everyone to contribute and keep the release branch clean and stable with only PRs that have been vetted by the maintainers. Of course this meens that there might be some PRs with more than one issue fixed or the dev branch becoming filled with unmerged fixes and features (I am being overly optimistic here ;-) .

**Comment by moylop260** [comment] 2019-02-27 22:30
Superseded by https://github.com/OCA/oca-github-bot/issues/24

**Closed by moylop260** 2019-02-27 22:30 UTC
Labels: help wanted
